sudo: required

services:
  - docker

before_install:
  - if [ "$TRAVIS_BRANCH" == "php7-xenial" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -f php7-xenial/Dockerfile --pull -t revenuewire/docker-php:php7-xenial .;
      docker push revenuewire/docker-php:php7-xenial;
    fi
  - if [ "$TRAVIS_BRANCH" == "php56-centos6" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -f php56-centos6/Dockerfile -t revenuewire/docker-php:php56-centos6 .;
      docker push revenuewire/docker-php:php56-centos6;
    fi
  - if [ "$TRAVIS_BRANCH" == "php56-centos6-jackfruit" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker build -f php56-centos6-jackfruit/Dockerfile -t revenuewire/docker-php:php56-centos6-jackfruit .;
        docker push revenuewire/docker-php:php56-centos6-jackfruit;
    fi
  - if [ "$TRAVIS_BRANCH" == "php56-centos6-jackfruit-no-xdebug" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker build -f php56-centos6-jackfruit-no-xdebug/Dockerfile -t revenuewire/docker-php:php56-centos6-jackfruit-no-xdebug .;
        docker push revenuewire/docker-php:php56-centos6-jackfruit-no-xdebug;
    fi

script:
  - echo `date`